const actionTypes = {
    GET_HOME: 'GET_HOME',
    GET_TOP100: 'GET_TOP100',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    LOADING: "LOADING",
    SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
    SET_CUR_ALBUM_ID: "SET_CUR_ALBUM_ID",
    SET_FAVOR:"SET_FAVOR",
    SET_RECENT:"SET_RECENT",
    DELETE_RECENT:"DELETE_RECENT",
    SET_USERS:"SET_USERS", 
    UPDATE_USER:"UPDATE_USER", 
    UPDATE_PASSWORD:"UPDATE_PASSWORD", 
    UPDATE_AVATAR:"UPDATE_AVATAR", 
    SET_USER_NOW:"SET_USER_NOW",
    CURRENT_WIDTH:"CURRENT_WIDTH",

    // music
    PLAY: "PLAY",
    PLAYLIST: "PLAYLIST",
    AT_ALBUM: "AT_ALBUM",
    SEARCH: "SEARCH",
}

export default actionTypes