const path = {
    PUBLIC: "/",
    HOME: "",
    LOGIN: 'login',
    USER: 'user-info',
    ADMIN: 'admin',
    STAR: '*',
    MY_MUSIC: "mymusic",
    ALBUM__TITLE__PID: "album/:title/:pid",
    PLAYLIST__TITLE__PID: "playlist/:title/:pid",
    WEEKRANK__TITLE__PID: "zing-chart-tuan/:title/:pid",
    ZING_CHART: "zing_chart",
    NEW_RELEASE: "moi-phat-hanh",
    TOP_100: "top100",
    SEARCH: "tim-kiem",
    ALL: "tat-ca",
    SONG: "bai-hat",
    // HOME__SINGER: ":singer",
    PLAYLIST__SEARCH: "playlist",
}
export default path;